PH2ANS_DIR: ../data/raw/Testing/Phase2Answers
PH1QUE_DIR: ../data/raw/Testing/Phase1Questions
GPTQUE_DIR: ../data/processed
GPTANS_DIR: ../data/interim
CAT_PATH: ../data/raw/subcategories-list.txt
REV_PATH: data/raw/reversals.txt
SELECTED_IDXS:
  - 2g
  - 2a
  - 10b
  - 7f
  - 4d
  - 4b
  - 1c
  - 6d
Q_TEMPLATE: 'In this line, based on the pairs provided, choose among them the least illustrative and the most illustrative representation for the kind of relation demonstrated by these examples: {}. The output should be these four pairs and the least illustrative and the most illustrative as the 5th and 6th column, accordingly. The output should be written in one line, 6 pairs overall in the following format: "pair1, pair2, pair3, pair4, least_illustrative, most_illustrative". And that is it, no brackets, no quotes, nothing else, it must be in this format. Do not include the examples of the relation in your output! They just provide you examples of a certain relation and based on this relation (that you infer from these examples) you need to choose the least and most illustrative among the following 4 pairs:'


